# Generated by Django 5.1.2 on 2024-11-03 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_set', to='main.test'),
        ),
        migrations.AddField(
            model_name='image',
            name='theory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_set', to='main.theory'),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer',
            field=models.TextField(),
        ),
    ]
